site_name: IoT-dev-setup
site_url: https://46265z.github.io/IoT-dev-setup/

nav:
  - Home: index.md
#  - About: about.md
  - Prerequisites: prerequisites.md
  - How To Test: add-device.md
  - "How To":
    - "Device Setup": HowTo/add-device.md
    - "Import Deploy": HowTo/import-code-from-github.md
    - "Integrate webhook": HowTo/integrate-webhook.md
    - "Test the hook": HowTo/test-pybytes-webhook.md
      #  - Page2: page2.md
      #  - Section1:
      #    - Subpage1: subpage1.md
      #    - Subpage2: subpage2.md
theme:
  name: material
# Use extra CSS to customize styles, based on theme
extra_css:
  - stylesheets/extra.css
